steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - asia-south1-docker.pkg.dev/noonprd-biadmon/cloud-run-source-deploy/bq-test-app
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - asia-south1-docker.pkg.dev/noonprd-biadmon/cloud-run-source-deploy/bq-test-app

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

serviceAccount: projects/noonprd-biadmon/serviceAccounts/admon-analytics@noonprd-biadmon.iam.gserviceaccount.com